FROM openjdk:11
ARG JAR_FILE=target/*.jar
ARG BUILD_PORT=8081
ENV SERVER_PORT=$BUILD_PORT
ENV DATASOURCE_URL="jdbc:mysql://mysqldb:3306/bootdb"
ENV DATASOURCE_USERNAME="root"
ENV DATASOURCE_PASSWORD="root"
ENV STOCK_MANAGER_STOCK_URL="http://localhost:8080/stock"
ENV STOCK_MANAGER_NOTIFICATION_URL="http://localhost:8080/notification"
ENV STOCK_MANAGER_NOTIFICATION_HOST="localhost"
ENV STOCK_MANAGER_NOTIFICATION_PORT=$SERVER_PORT
EXPOSE $SERVER_PORT
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]